baseurl = "http://JimAmuro.github.io/"
languageCode = "en-us"
title = "Jim Amuro"
theme = "hyde"
hasCJKLanguage = true
pygmentsstyle = "default"
SectionPagesMenu = "main"
[[menu.main]]
    name = "My GitHub"
    weight = 21
    identifier = "GH"
    url = "https://github.com/JimAmuro"

[params]
    description = "Pursuing non-trivial truth through intuition and deduction."
    author = "Hui Sun"
    themeColor = "theme-base-0d"
    disqusShortname = "jimgithub"
    copyright= "Built by Hui Sun using "
